// Mocks generated by Mockito 5.4.6 from annotations
// in exchek/test/views/account_setup_view_test/business_account_setup_view_test/proceed_with_kyc_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cron/cron.dart' as _i5;
import 'package:exchek/core/utils/exports.dart' as _i2;
import 'package:exchek/viewmodels/account_setup_bloc/account_type_selection/account_type_selection_bloc.dart'
    as _i3;
import 'package:exchek/viewmodels/account_setup_bloc/personal_account_setup_bloc/personal_account_setup_bloc.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBusinessAccountSetupState_0 extends _i1.SmartFake
    implements _i2.BusinessAccountSetupState {
  _FakeBusinessAccountSetupState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountTypeState_1 extends _i1.SmartFake
    implements _i3.AccountTypeState {
  _FakeAccountTypeState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthState_2 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonalAccountSetupState_3 extends _i1.SmartFake
    implements _i4.PersonalAccountSetupState {
  _FakePersonalAccountSetupState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BusinessAccountSetupBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessAccountSetupBloc extends _i1.Mock
    implements _i2.BusinessAccountSetupBloc {
  MockBusinessAccountSetupBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cron(_i5.Cron? _cron) => super.noSuchMethod(
    Invocation.setter(#cron, _cron),
    returnValueForMissingStub: null,
  );

  @override
  _i2.BusinessAccountSetupState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeBusinessAccountSetupState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.BusinessAccountSetupState);

  @override
  _i6.Stream<_i2.BusinessAccountSetupState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.BusinessAccountSetupState>.empty(),
          )
          as _i6.Stream<_i2.BusinessAccountSetupState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.FileData?> getFileDataFromPath(
    String? path,
    String? fallbackName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFileDataFromPath, [path, fallbackName]),
            returnValue: _i6.Future<_i2.FileData?>.value(),
          )
          as _i6.Future<_i2.FileData?>);

  @override
  _i6.Future<_i2.FileData?> downloadFileDataFromUrl(
    String? url,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFileDataFromUrl, [url, name]),
            returnValue: _i6.Future<_i2.FileData?>.value(),
          )
          as _i6.Future<_i2.FileData?>);

  @override
  _i6.Future<List<_i2.KycVerificationSteps>> getAvailableSteps() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableSteps, []),
            returnValue: _i6.Future<List<_i2.KycVerificationSteps>>.value(
              <_i2.KycVerificationSteps>[],
            ),
          )
          as _i6.Future<List<_i2.KycVerificationSteps>>);

  @override
  void add(_i2.BusinessAccountSetupEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i2.BusinessAccountSetupEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.BusinessAccountSetupState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i2.BusinessAccountSetupEvent>(
    _i2.EventHandler<E, _i2.BusinessAccountSetupState>? handler, {
    _i2.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i2.Transition<
      _i2.BusinessAccountSetupEvent,
      _i2.BusinessAccountSetupState
    >?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i2.Change<_i2.BusinessAccountSetupState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AccountTypeBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountTypeBloc extends _i1.Mock implements _i3.AccountTypeBloc {
  MockAccountTypeBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AccountTypeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAccountTypeState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AccountTypeState);

  @override
  _i6.Stream<_i3.AccountTypeState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i3.AccountTypeState>.empty(),
          )
          as _i6.Stream<_i3.AccountTypeState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.AccountTypeEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.AccountTypeEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AccountTypeState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.AccountTypeEvent>(
    _i2.EventHandler<E, _i3.AccountTypeState>? handler, {
    _i2.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i2.Transition<_i3.AccountTypeEvent, _i3.AccountTypeState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i2.Change<_i3.AccountTypeState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i2.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_2(this, Invocation.getter(#state)),
          )
          as _i2.AuthState);

  @override
  _i6.Stream<_i2.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.AuthState>.empty(),
          )
          as _i6.Stream<_i2.AuthState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void add(_i2.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i2.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i2.AuthEvent>(
    _i2.EventHandler<E, _i2.AuthState>? handler, {
    _i2.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i2.Transition<_i2.AuthEvent, _i2.AuthState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i2.Change<_i2.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PersonalAccountSetupBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonalAccountSetupBloc extends _i1.Mock
    implements _i4.PersonalAccountSetupBloc {
  MockPersonalAccountSetupBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set cron(_i5.Cron? _cron) => super.noSuchMethod(
    Invocation.setter(#cron, _cron),
    returnValueForMissingStub: null,
  );

  @override
  _i4.PersonalAccountSetupState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePersonalAccountSetupState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.PersonalAccountSetupState);

  @override
  _i6.Stream<_i4.PersonalAccountSetupState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.PersonalAccountSetupState>.empty(),
          )
          as _i6.Stream<_i4.PersonalAccountSetupState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<_i2.FileData?> getFileDataFromPath(
    String? path,
    String? fallbackName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFileDataFromPath, [path, fallbackName]),
            returnValue: _i6.Future<_i2.FileData?>.value(),
          )
          as _i6.Future<_i2.FileData?>);

  @override
  _i6.Future<_i2.FileData?> downloadFileDataFromUrl(
    String? url,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFileDataFromUrl, [url, name]),
            returnValue: _i6.Future<_i2.FileData?>.value(),
          )
          as _i6.Future<_i2.FileData?>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void add(_i4.PersonalAccountSetupEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i4.PersonalAccountSetupEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.PersonalAccountSetupState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i4.PersonalAccountSetupEvent>(
    _i2.EventHandler<E, _i4.PersonalAccountSetupState>? handler, {
    _i2.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i2.Transition<
      _i4.PersonalAccountSetupEvent,
      _i4.PersonalAccountSetupState
    >?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i2.Change<_i4.PersonalAccountSetupState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
