name: docker-build-run

on:
  push:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v5

      # Step 2: Stop old container if exists
      - name: Stop old container
        run: |
          if (docker ps -q -f name=myapp-container) {
              docker stop myapp-container
          }
          if (docker ps -aq -f name=myapp-container) {
              docker rm myapp-container
          }

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t myapp-image ./exchek-ui-dev-development/ 

      # Step 4: Run new container mapping ports (host:container)
      - name: Run Docker container
        run: docker run -d -p 8082:80 --name myapp-container myapp-image

      # Step 5: Show running containers
      - name: List running containers
        run: docker ps -a

      # Step 6: Test the app
      - name: Test running container
        run: |
          try {
              Invoke-WebRequest http://localhost:8082/exchek -UseBasicParsing
              Write-Host "Container is running successfully!"
          } catch {
              Write-Error "Container did not start properly!"
              exit 1
          }
